grupo/urls.py
from django.urls import path, include
from .views import VerGrupo, CriarGrupo, AtualizarGrupo, ApagarGrupo
from django.contrib import admin

app_name = 'grupo'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('grupo/criar/', CriarGrupo.as_view(), name='criar'),
    path('<int:pk>/', VerGrupo.as_view(), name='grupo'),
    path('<int:pk>/atualizar/', AtualizarGrupo.as_view(), name='atualizar'),
    path('<int:pk>/apagar/', ApagarGrupo.as_view(), name='apagar'),
]

home/urls.py
from django.urls import path

from .views import Index, get_subgrupos, get_tarefas, Grupos, SubGrupos, Tarefas


app_name = 'home'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('get/subgrupos/<int:id_grupo>', get_subgrupos),
    path('get/tarefas/<int:id_subgrupo>', get_tarefas),
    path('grupos/', Grupos.as_view(), name='grupos'),
    path('subgrupos/', SubGrupos.as_view(), name='subgrupos'),
    path('tarefas/', Tarefas.as_view(), name='tarefas'),
]

subgrupo/urls.py
from django.urls import path, include
from .views import VisualizarSubGrupo, MostraSubGrupo, CriarSubGrupo, exclui_subgrupo, edita_subgrupo

app_name = 'subgrupo'

urlpatterns = [
    path('subgrupo/criar/', CriarSubGrupo.as_view(), name='criar'),
    path('atualizar/<slug_subgrupo>/', edita_subgrupo, name='atualizar'),
    path('apagar/<slug_subgrupo>/', exclui_subgrupo, name='apagar'),
    path('mostra/<slug_subgrupo>/', MostraSubGrupo.as_view(), name='mostra'),
    path('<slug_subgrupo>/', VisualizarSubGrupo.as_view(), name='subgrupo'),
]

tarefa/urls.py
from django.urls import path
from .views import CriarTarefa, EditarTarefa, ExcluirTarefa


app_name = 'tarefa'

urlpatterns = [
    path('tarefa/criar/', CriarTarefa.as_view(), name='criar'),
    path('<int:pk>/atualizar/', EditarTarefa.as_view(), name='atualizar'),
    path('<int:pk>/apagar/', ExcluirTarefa.as_view(), name='apagar'),
]

to_do_novo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('', include('grupo.urls')),
    path('admin/', admin.site.urls),
    path('conta/', include('conta.urls')),
    path('<int:pk>/', include('subgrupo.urls')),
    path('<int:pk>/<int:pk>/', include('tarefa.urls')),
]

home/models.py
from django.db import models

# Create your models here.

subgrupo/models.py
from django.db.models import CASCADE
from django.db.models import CharField
from django.db.models import ForeignKey
from django.db.models import Model
from django.db.models import SlugField
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

from grupo.models import Grupo


class SubGrupo(Model):
    nome = CharField(max_length=10000)
    grupo = ForeignKey(Grupo, on_delete=CASCADE)
    user = ForeignKey(User, on_delete=CASCADE)
    slug = SlugField(null=True, blank=True)

    def __str__(self):
        return self.nome

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.nome)

        super(SubGrupo, self).save(*args, **kwargs)

tarefa/models.py
from django.db.models import Model
from django.db.models import ForeignKey
from django.db.models import CASCADE
from django.db.models import CharField
from django.db.models import TextField
from django.db.models import BooleanField
from django.db.models import DateTimeField
from django.db.models import SlugField
from django.contrib.auth.models import User
from django.urls import reverse
from django.template.defaultfilters import slugify

from grupo.models import Grupo
from subgrupo.models import SubGrupo

class Tarefa(Model):
    orgao = CharField(max_length=10000)
    resposta = TextField(max_length=10000, null=True, blank=True)
    comentario = TextField(max_length=10000, null=True, blank=True)
    revisado = BooleanField()
    created = DateTimeField(auto_now_add=True)
    slug = SlugField(null=True, blank=True)
    user = ForeignKey(User, on_delete=CASCADE)
    grupo = ForeignKey(Grupo, on_delete=CASCADE, null=True)
    subgrupo = ForeignKey(SubGrupo, on_delete=CASCADE)

    def __str__(self):
        return self.orgao

    def get_absolute_url(self):
        return reverse('subgrupos', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.orgao)

        super(Tarefa, self).save(*args, **kwargs)

    class Meta:
        ordering = ['revisado']

home/forms.py
from django.forms import ModelForm
from .models import Grupos, Tarefa, Sub_Grupos

class GruposForm(ModelForm):
    class Meta:
        model = Grupos
        fields = '__all__'

class TarefasForm(ModelForm):
    class Meta:
        model = Tarefa
        fields = ['title', 'description', 'complete']


class Sub_GruposForm(ModelForm):
    class Meta:
        model = Sub_Grupos
        fields = ['nome_subgrupo']

subgrupo/forms.py
from django.forms import ModelForm
from .models import SubGrupo

class SubGrupoForm(ModelForm):
    class Meta:
        model = SubGrupo
        fields = ['nome']

tarefa/forms.py
from django.forms import ModelForm
from .models import Tarefa


class TarefaForm(ModelForm):
    class Meta:
        model = Tarefa
        fields = ['orgao', 'resposta', 'comentario', 'revisado']

home/views.py
from django.core.serializers import serialize
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render
from django.views.generic import View

from grupo.models import Grupo
from subgrupo.models import SubGrupo
from tarefa.models import Tarefa


class Index(LoginRequiredMixin, View):

    def get(self, request):

        grupos = Grupo.objects.all()

        return render(request, "home/index.html", {'grupos': grupos})

def get_subgrupos(request, id_grupo):

    if request.method == 'GET':
        grupo = get_object_or_404(Grupo, id=id_grupo)
        subgrupos = list(grupo.subgrupo_set.all().values('id', 'nome'))
        
        return JsonResponse({'subgrupos': subgrupos})   


def get_tarefas(request, id_subgrupo):

    if request.method == 'GET':
        subgrupo = get_object_or_404(SubGrupo, id=id_subgrupo)
        tarefas = list(subgrupo.tarefa_set.all().values('id', 'title'))
        
        return JsonResponse({'tarefas': tarefas})  
        

class Grupos(LoginRequiredMixin, View):

    def get(self, request):
        busca = request.GET.get('busca', '')
        grupos = Grupo.objects.filter(user=request.user)
        if busca:
            grupos = grupos.filter(nome__icontains=busca)

        context = {'grupos': grupos, 'busca': busca}

        return render(request, "home/grupos.html", context)


class SubGrupos(LoginRequiredMixin, View):

    def get(self, request):
        busca = request.GET.get('busca', '')
        subgrupos = SubGrupo.objects.filter(user=request.user)
        if busca:
            subgrupos = subgrupos.filter(nome__icontains=busca)

        context = {'subgrupos': subgrupos, 'busca': busca}

        return render(request, "home/subgrupos.html", context)


class Tarefas(LoginRequiredMixin, View):

    def get(self, request):
        busca = request.GET.get('busca', '')
        tarefas = Tarefa.objects.filter(user=request.user)
        if busca:
            tarefas = tarefas.filter(nome__icontains=busca)

        context = {'tarefas': tarefas, 'busca': busca}

        return render(request, "home/tarefas.html", context)

subgrupo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template.defaultfilters import slugify
from django.views.generic.list import ListView
from django.views.generic import CreateView, View
from django.views.generic.edit import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from grupo.models import Grupo

from .forms import SubGrupoForm
from .models import SubGrupo

from braces.views import GroupRequiredMixin


class CriarSubGrupo(GroupRequiredMixin, LoginRequiredMixin, View):
    group_required = (u"SGCE", u"Inspetores Gerais")
    template_name = 'subgrupo/formulario_subgrupo.html'
    form_model = SubGrupoForm

    def get(self, request, slug_grupo):
        form = self.form_model(request.GET)
        return render(request, self.template_name, {'form': form, 'slug_grupo': slug_grupo})

    def post(self, request, slug_grupo):

        grupo = get_object_or_404(Grupo, slug=slug_grupo)
        form = self.form_model(request.POST)
        if form.is_valid():
            formulario = form.save(commit=False)
            formulario.grupo = grupo
            formulario.user = request.user
            formulario.save()
            return redirect(f'/{grupo.slug}/')
        else:
            return render(request, self.template_name, {'form': form, 'slug_grupo': slug_grupo})

class VisualizarSubGrupo(GroupRequiredMixin, LoginRequiredMixin, ListView):
    group_required = (u"Auditores", u"SGCE", u"Inspetores Gerais", u"Supervisores")

    def get(self, request, slug_grupo, slug_subgrupo):
        busca = request.GET.get('search-area', '')
        subgrupo = get_object_or_404(SubGrupo, slug=slug_subgrupo, grupo__slug=slug_grupo)
        tarefas = subgrupo.tarefa_set.all()

        if busca:
            tarefas = tarefas.filter(nome___icontains=busca)

        context = {'tarefas': tarefas, 'subgrupo': subgrupo, 'search_input': busca}

        return render(request, "subgrupo/subgrupo.html", context)


class MostraSubGrupo(GroupRequiredMixin, LoginRequiredMixin, View):
    group_required = (u"Auditores", u"SGCE", u"Inspetores Gerais", u"Supervisores")

    def get(self, request, pk):
        subgrupo_especifico = SubGrupo.objects.get(id=pk)
        join_subgrupo = subgrupo_especifico.tarefa_subgrupos.all()
        id_grupo = subgrupo_especifico.grupo_sub_id

        busca = request.GET.get('search-area', '')

        if busca:
            join_subgrupo = join_subgrupo.filter(title__icontains=busca)

        context = {'join_subgrupo': join_subgrupo, 'pk': pk, 'search_input': busca, 'id_grupo': id_grupo}

        return render(request, "login/mostra_subgrupo.html", context)

class exclui_subgrupo(GroupRequiredMixin, LoginRequiredMixin, View):
    group_required = (u"SGCE", u"Inspetores Gerais")

    template_name = 'tarefa/excluir_subgrupo.html'
    model_form = SubGrupoForm

    def get(self, request, slug_grupo, pk):
        grupo = get_object_or_404(Grupo, slug=slug_grupo)
        subgrupo = get_object_or_404(SubGrupo, slug=slug_subgrupo)

        return render(request, self.template_name, {'subgrupo': subgrupo, 'grupo': slug_grupo})

    def post(self, request, slug_grupo, slug_subgrupo, pk):
        grupo = get_object_or_404(Grupo, slug=slug_grupo)
        subgrupo = get_object_or_404(SubGrupo, grupo=grupo, slug=slug_subgrupo)

        subgrupo.delete()

        return redirect('grupo:grupo', slug_grupo)

def edita_subgrupo(request, pk):
    item_id = SubGrupo.objects.get(id=pk)
    id_grupo = item_id.grupo_sub_id

    if request.method == 'POST':
        item = get_object_or_404(SubGrupo, id=pk)
        form = SubGrupoForm(request.POST, instance=item)

        if form.is_valid():
            form.save()
            return redirect(f'/subgrupos/{id_grupo}')
    else:
        item = SubGrupo.objects.filter(id=pk).values().last()
        form = SubGrupoForm(initial=item)

    return render(request, 'login/formulario_subgrupos.html', {'pk': pk, 'form': form, 'id_grupo': id_grupo})


def atualiza_subgrupo(request, pk):
    item = SubGrupo.objects.get(id=pk)
    id_grupo = item.grupo_sub_id

    if request.method == 'POST':
        item.delete()
        return redirect(f'/subgrupos/{id_grupo}')

    return render(request, 'login/apagar_subgrupo.html', {'pk': pk, 'id_grupo': id_grupo})


class AtualizarSubGrupo(LoginRequiredMixin, UpdateView):
    model = SubGrupo
    fields = '__all__'
    template_name = 'login/formulario_subgrupos.html'

tarefa/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import View
from django.views.generic.edit import UpdateView, DeleteView

from grupo.models import Grupo
from subgrupo.models import SubGrupo

from .models import Tarefa
from .forms import TarefaForm
from braces.views import GroupRequiredMixin



class CriarTarefa(GroupRequiredMixin, LoginRequiredMixin, View):
    group_required = (u"SGCE", u"Inspetores Gerais", u"Supervisores")
    template_name = 'tarefa/criar_tarefa.html'
    form_model = TarefaForm
    
    def get(self, request, slug_grupo, slug_subgrupo):
        
        form = self.form_model(request.GET)
        return render(request, self.template_name, {'form': form, 'slug_grupo': slug_grupo, 'slug_subgrupo': slug_subgrupo})

    def post(self, request, slug_grupo, slug_subgrupo):

        grupo = get_object_or_404(Grupo, slug=slug_grupo)
        subgrupo = get_object_or_404(SubGrupo, slug=slug_subgrupo)
        form = self.form_model(request.POST)
        if form.is_valid():
            formulario = form.save(commit=False)
            formulario.grupo = grupo
            formulario.subgrupo = subgrupo
            formulario.user = request.user
            formulario.save()
            return redirect('subgrupo:subgrupo', slug_grupo, slug_subgrupo)
        else:
            return render(request, self.template_name, {'form': form, 'slug_grupo': slug_grupo})


class EditarTarefa(GroupRequiredMixin, LoginRequiredMixin, View):
    group_required = (u"SGCE", u"Inspetores Gerais", u"Supervisores")
    template_name = 'tarefa/editar_tarefa.html'
    model_form = TarefaForm

    def get(self, request, slug_grupo, slug_subgrupo, pk):
        grupo = get_object_or_404(Grupo, slug=slug_grupo)
        subgrupo = get_object_or_404(SubGrupo, slug=slug_subgrupo)
        tarefa = get_object_or_404(Tarefa, grupo=grupo, subgrupo=subgrupo, id=pk)
        form = self.model_form(instance=tarefa)
        
        return render(request, self.template_name, {'form': form, 'grupo':slug_grupo, 'subgrupo': slug_subgrupo})

    def post(self, request, slug_grupo, slug_subgrupo, pk):
        grupo = get_object_or_404(Grupo, slug=slug_grupo)
        subgrupo = get_object_or_404(SubGrupo, grupo=grupo, slug=slug_subgrupo)
        tarefa = get_object_or_404(Tarefa, grupo=grupo, subgrupo=subgrupo, id=pk)
        
        form = self.model_form(request.POST, instance=tarefa)
        if form.is_valid():
            form.save()
            return redirect('subgrupo:subgrupo', slug_grupo, slug_subgrupo)
        else:
            return render(request, self.template_name, {'form': form})

class ExcluirTarefa(GroupRequiredMixin, LoginRequiredMixin, View):
    group_required = (u"SGCE", u"Inspetores Gerais")

    template_name = 'tarefa/excluir_tarefa.html'
    model_form = TarefaForm

    def get(self, request, slug_grupo, slug_subgrupo, pk):
        grupo = get_object_or_404(Grupo, slug=slug_grupo)
        subgrupo = get_object_or_404(SubGrupo, slug=slug_subgrupo)
        tarefa = get_object_or_404(Tarefa, grupo=grupo, subgrupo=subgrupo, id=pk)
        
        return render(request, self.template_name, {'tarefa': tarefa, 'grupo': slug_grupo, 'subgrupo': slug_subgrupo})

    def post(self, request, slug_grupo, slug_subgrupo, pk):
        grupo = get_object_or_404(Grupo, slug=slug_grupo)
        subgrupo = get_object_or_404(SubGrupo, grupo=grupo, slug=slug_subgrupo)
        tarefa = get_object_or_404(Tarefa, grupo=grupo, subgrupo=subgrupo, id=pk)
        
        tarefa.delete()

        return redirect('subgrupo:subgrupo', slug_grupo, slug_subgrupo)

   

templates/home/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class='header-bar'>

    {% if request.user.is_authenticated %}
       <a href="{% url 'logout' %}">Sair</a>
    {% else %}
        <a href="{% url 'login' %}">Entrar</a>
    {% endif %}
</div>

<h1>Lei Geral de Proteção de Dados - Assuntos</h1>

<div id="search-add-wrapper">
<form method="GET">
    <input type="text" name="busca" value="{{ busca }}">
    <input type="submit" value="Search">
</form>
    <a id="add-link" href="{% url 'grupo:criar' %}">&#x2b;</a>
</div>

<div id="tasklist" class="task-items-wrapper">
    {% for grupo in grupos %}

        <div class="task-wrapper" data-position="{{ grupo.pk }}">
            <div class="task-title">
                <div class="task-complete-icon"></div>
                <a href="{% url 'grupo:grupo' grupo.slug %}">{{ grupo }}</a>
            </div>
            <div class="task-controls">
                <a class="delete-link" href="{% url 'grupo:apagar' grupo.id %}">&#215;</a>
                <a class="update-link" href="{% url 'grupo:atualizar' grupo.id %}">&nbsp;&#10247;</a>
            </div>
        </div>

    {% empty %}
        <h3>No items in list</h3>
    {% endfor %}

</div>

{% endblock content %}

templates/home/subgrupos.html
{% extends 'base.html' %}

{% block content %}

<div class='header-bar'>
    <div>
        <h1>Seja bem-vindo, {{ request.user.first_name }}</h1>
        <h3 style="margin:0">Você tem <i>{{ incompletos }}</i> respostas revisadas.</h3>
    </div>

{% if request.user.is_authenticated %}
       <a href="{% url 'logout' %}">Sair</a>
    {% else %}
        <a href="{% url 'login' %}">Entrar</a>
{% endif %}
</div>

<h1>Questionário</h1>

<div id="tasklist" class="task-items-wrapper">
    {% for subgrupo in subgrupos %}

        <div class="task-wrapper" data-position="{{ grupo.pk }}">
            <div class="task-title">
                <div class="task-complete-icon"></div>
                <a href="{% url 'subgrupo:subgrupo' subgrupo.grupo.slug subgrupo.slug %}">{{ subgrupo }}</a>
            </div>
            <div class="task-controls">
                <a class="delete-link" href="{% url 'subgrupo:apagar' subgrupo.grupo.slug subgrupo.id %}">&#215;</a>
                <a class="update-link" href="{% url 'subgrupo:atualizar' subgrupo.grupo.slug subgrupo.id %}">&nbsp;&#10247;</a>
            </div>
        </div>

    {% empty %}
        <h3>Sem itens na lista</h3>
    {% endfor %}

</div>

{% endblock content %}

templates/home/tarefas.html
{% extends 'base.html' %}
{% block content %}


<div class='header-bar'>
    <div>
        <h1>Hello, {{ request.user.first_name }}</h1>
    </div>

{% if request.user.is_authenticated %}
       <a href="{% url 'logout' %}">Sair</a>
    {% else %}
        <a href="{% url 'login' %}">Entrar</a>
{% endif %}
</div>



<h1>Minhas Tarefas</h1>

<div id="search-add-wrapper">
<form method="GET">
    <input type="text" name="search-area" value="{{ search_input }}">
    <input type="submit" value="Search">
</form>
    <a id="add-link" href="">&#x2b;</a>
</div>

<div id="tasklist" class="task-items-wrapper">
    {% for tarefa in tarefas %}

    <div class="task-wrapper" data-position="{{grupo.pk}}">
        <div class="task-title">
            {% if tarefa.complete %}
            <div class="task-complete-icon"></div>
            <a href="{% url 'tarefa:atualizar' tarefa.grupo.slug tarefa.subgrupo.slug tarefa.slug %}">{{ tarefa }}</a>
            {% else %}
            <div class="task-incomplete-icon"></div>
            <a href="{% url 'tarefa:atualizar' tarefa.grupo.slug tarefa.subgrupo.slug tarefa.slug %}">{{ tarefa }}</a>
            {% endif %}
        </div>
        <div class="task-controls">
            <a class="delete-link" href="{% url 'tarefa:apagar' tarefa.grupo.slug tarefa.subgrupo.slug tarefa.slug %}">&#215;</a>
            <span class="handle">&nbsp;&#10247;</span>
        </div>
    </div>

    {% empty %}
    <h3>No items in list</h3>
    {% endfor %}

</div>

<h1>Powered by CIEG</h1>

{% endblock content %}