grupo/urls.py
from django.urls import path, include
from .views import VerGrupo, CriarGrupo, AtualizarGrupo, ApagarGrupo
from django.contrib import admin

app_name = 'grupo'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('grupo/criar/', CriarGrupo.as_view(), name='criar'),
    path('<int:pk>/', VerGrupo.as_view(), name='grupo'),
    path('<int:pk>/atualizar/', AtualizarGrupo.as_view(), name='atualizar'),
    path('<int:pk>/apagar/', ApagarGrupo.as_view(), name='apagar'),
]

home/urls.py
from django.urls import path

from .views import Index, get_subgrupos, get_tarefas, Grupos, SubGrupos, Tarefas


app_name = 'home'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('get/subgrupos/<int:id_grupo>', get_subgrupos),
    path('get/tarefas/<int:id_subgrupo>', get_tarefas),
    path('grupos/', Grupos.as_view(), name='grupos'),
    path('subgrupos/', SubGrupos.as_view(), name='subgrupos'),
    path('tarefas/', Tarefas.as_view(), name='tarefas'),
]

subgrupo/urls.py
from django.urls import path, include
from .views import VisualizarSubGrupo, MostraSubGrupo, CriarSubGrupo, exclui_subgrupo, edita_subgrupo

app_name = 'subgrupo'

urlpatterns = [
    path('subgrupo/criar/', CriarSubGrupo.as_view(), name='criar'),
    path('atualizar/<slug_subgrupo>/', edita_subgrupo, name='atualizar'),
    path('apagar/<slug_subgrupo>/', exclui_subgrupo, name='apagar'),
    path('mostra/<slug_subgrupo>/', MostraSubGrupo.as_view(), name='mostra'),
    path('<slug_subgrupo>/', VisualizarSubGrupo.as_view(), name='subgrupo'),
]

to_do_novo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('', include('grupo.urls')),
    path('admin/', admin.site.urls),
    path('conta/', include('conta.urls')),
    path('<int:pk>/', include('subgrupo.urls')),
    path('<int:pk>/<int:pk>/', include('tarefa.urls')),
]

grupo/models.py
from django.db.models import Model
from django.db.models import CharField
from django.db.models import SlugField
from django.db.models import CASCADE
from django.db.models import ForeignKey
from django.db.models import URLField
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


class Grupo(Model):
    nome = CharField(max_length=1000, unique=True)
    user = ForeignKey(User, on_delete=CASCADE)
    slug = SlugField(null=True, blank=True)

    def __str__(self):
        return self.nome

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.nome)

        super(Grupo, self).save(*args, **kwargs)

grupo/forms.py
from django.forms import ModelForm
from .models import Grupo

class GrupoForm(ModelForm):
    class Meta:
        model = Grupo
        fields = '__all__'

grupo/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import GroupRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Grupo


class VerGrupo(LoginRequiredMixin, GroupRequiredMixin, View):
    group_required = (u"Auditores", u"SGCE", u"Inspetores Gerais", u"Supervisores")

    def get(self, request, slug_grupo):
        busca = request.GET.get('busca', '')
        grupo = get_object_or_404(Grupo, slug=slug_grupo)
        subgrupos = grupo.subgrupo_set.all()

        if busca:
            subgrupos = subgrupos.filter(nome__icontains=busca)

        context = {'grupo': grupo, 'subgrupos': subgrupos, 'busca': busca}

        return render(request, "grupo/grupo.html", context)


class CriarGrupo(LoginRequiredMixin, GroupRequiredMixin, CreateView):
    group_required = u"SGCE"
    model = Grupo
    context_object_name = 'criar_grupo'
    success_url = reverse_lazy('home:index')
    fields = ('nome',)
    template_name = 'grupo/formulario_grupo.html'

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        in_group = False
        if request.user.is_authenticated:
            in_group = self.check_membership(self.get_group_required())
            if not in_group:
                return self.handle_no_permission(request)
        return super(GroupRequiredMixin, self).dispatch(
                request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CriarGrupo, self).form_valid(form)

class AtualizarGrupo(LoginRequiredMixin, GroupRequiredMixin, UpdateView):
    group_required = (u"SGCE", u"Inspetores Gerais", u"Supervisores")
    model = Grupo
    fields = '__all__'
    success_url = reverse_lazy('grupo')
    template_name = 'login/formulario_grupos.html'


class ApagarGrupo(LoginRequiredMixin, GroupRequiredMixin, DeleteView):
    group_required = (u"SGCE", u"Inspetores Gerais")
    model = Grupo
    fields = '__all__'
    # success_url = reverse_lazy('grupo:grupo', kwargs={'pk': self.object.pk})
    template_name = 'grupo/excluir_grupo.html'

    def get_success_url(self):
        # Se não quiser usar o get_absolute_url e quiser passar
        # a instância criada para redirecionar manualmente...
        return reverse_lazy('grupo:grupo', kwargs={'pk': self.object.pk})

templates/grupo/excluir_grupo.html
{% extends 'base.html' %}
{% block content %}

<a href="{% url 'grupo:grupo' %} ">Retornar</a>

<form method='POST'>
  {% csrf_token %}
  <p>Tem certeza de que deseja apagar o assunto {{ grupo }} ?</p>
  <input type="submit" value="ApagaGrupo">
</form>

{% endblock content %}

templates/grupo/formulario_grupo.html
{% extends 'base.html' %}
{% block content %}

<h3>Adicionar Assunto</h3>

<a href="{% url 'home:index' %}">Retornar</a>

<form method="POST" action="">

  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="enviar">

</form>

{% endblock content %}

templates/grupo/grupo.html
{% extends 'base.html' %}
{% block content %}

  {% include "nav.html" %}

<div class='header-bar'>
    <div>
        <h1>Seja bem-vindo, {{ request.user.first_name }}</h1>
        <h3 style="margin:0">Você tem <i>{{ count }}</i> respostas revisadas.</h3>
        <h3 style="margin:0"> <a href="{% url 'home:index' %}">Assuntos</a></h3>
    </div>

{% if request.user.is_authenticated %}
       <a href="{% url 'logout' %}">Sair</a>
    {% else %}
        <a href="{% url 'login' %}">Entrar</a>
{% endif %}
</div>

<div id="search-add-wrapper">
    <a id="add-link" href="{% url 'subgrupo:criar' grupo.slug %}">&#x2b;</a>
</div>

<h1>Questionário</h1>
<div id="tasklist" class="task-items-wrapper">
    {% for subgrupo in subgrupos %}

    <div class="task-wrapper" data-position="{{ subgrupo.pk }}">
        <div class="task-title">
            <div class="task-complete-icon"></div>
            <a href="{ url 'subgrupo:subgrupo' grupo.slug subgrupo.slug %}">{{ subgrupo }}</a>
        </div>
        <div class="task-controls">
            <a class="delete-link" href="{ url 'subgrupo:apagar' subgrupo.grupo.slug subgrupo.slug %}">&#215;</a>
            <a class="update-link" href="{ url 'subgrupo:atualizar' subgrupo.grupo.slug subgrupo.slug %}">&nbsp;&#10247;</a>
        </div>
    </div>

    {% empty %}
    <h3>Sem itens na lista</h3>
    {% endfor %}

</div>

<h1>Powered by CIEG</h1>

{% endblock content %}