grupo/urls.py
from django.urls import path, include
from .views import VerGrupo, CriarGrupo, AtualizarGrupo, ApagarGrupo
from django.contrib import admin

app_name = 'grupo'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('grupo/criar/', CriarGrupo.as_view(), name='criar'),
    path('<int:pk>/', VerGrupo.as_view(), name='grupo'),
    path('<int:pk>/atualizar/', AtualizarGrupo.as_view(), name='atualizar'),
    path('<int:pk>/apagar/', ApagarGrupo.as_view(), name='apagar'),
]

home/urls.py
from django.urls import path

from .views import Index, get_subgrupos, get_tarefas, Grupos, SubGrupos, Tarefas


app_name = 'home'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('get/subgrupos/<int:id_grupo>', get_subgrupos),
    path('get/tarefas/<int:id_subgrupo>', get_tarefas),
    path('grupos/', Grupos.as_view(), name='grupos'),
    path('subgrupos/', SubGrupos.as_view(), name='subgrupos'),
    path('tarefas/', Tarefas.as_view(), name='tarefas'),
]

subgrupo/urls.py
from django.urls import path, include
from .views import VisualizarSubGrupo, MostraSubGrupo, CriarSubGrupo, exclui_subgrupo, edita_subgrupo

app_name = 'subgrupo'

urlpatterns = [
    path('subgrupo/criar/', CriarSubGrupo.as_view(), name='criar'),
    path('atualizar/<slug_subgrupo>/', edita_subgrupo, name='atualizar'),
    path('apagar/<slug_subgrupo>/', exclui_subgrupo, name='apagar'),
    path('mostra/<slug_subgrupo>/', MostraSubGrupo.as_view(), name='mostra'),
    path('<slug_subgrupo>/', VisualizarSubGrupo.as_view(), name='subgrupo'),
]

tarefa/urls.py
from django.urls import path
from .views import CriarTarefa, EditarTarefa, ExcluirTarefa


app_name = 'tarefa'

urlpatterns = [
    path('tarefa/criar/', CriarTarefa.as_view(), name='criar'),
    path('<int:pk>/atualizar/', EditarTarefa.as_view(), name='atualizar'),
    path('<int:pk>/apagar/', ExcluirTarefa.as_view(), name='apagar'),
]

to_do_novo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('', include('grupo.urls')),
    path('admin/', admin.site.urls),
    path('conta/', include('conta.urls')),
    path('<int:pk>/', include('subgrupo.urls')),
    path('<int:pk>/<int:pk>/', include('tarefa.urls')),
]

subgrupo/models.py
from django.db.models import CASCADE
from django.db.models import CharField
from django.db.models import ForeignKey
from django.db.models import Model
from django.db.models import SlugField
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

from grupo.models import Grupo


class SubGrupo(Model):
    nome = CharField(max_length=10000)
    grupo = ForeignKey(Grupo, on_delete=CASCADE)
    user = ForeignKey(User, on_delete=CASCADE)
    slug = SlugField(null=True, blank=True)

    def __str__(self):
        return self.nome

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.nome)

        super(SubGrupo, self).save(*args, **kwargs)

subgrupo/forms.py
from django.forms import ModelForm
from .models import SubGrupo

class SubGrupoForm(ModelForm):
    class Meta:
        model = SubGrupo
        fields = ['nome']

subgrupo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template.defaultfilters import slugify
from django.views.generic.list import ListView
from django.views.generic import CreateView, View
from django.views.generic.edit import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from grupo.models import Grupo

from .forms import SubGrupoForm
from .models import SubGrupo

from braces.views import GroupRequiredMixin


class CriarSubGrupo(GroupRequiredMixin, LoginRequiredMixin, View):
    group_required = (u"SGCE", u"Inspetores Gerais")
    template_name = 'subgrupo/formulario_subgrupo.html'
    form_model = SubGrupoForm

    def get(self, request, slug_grupo):
        form = self.form_model(request.GET)
        return render(request, self.template_name, {'form': form, 'slug_grupo': slug_grupo})

    def post(self, request, slug_grupo):

        grupo = get_object_or_404(Grupo, slug=slug_grupo)
        form = self.form_model(request.POST)
        if form.is_valid():
            formulario = form.save(commit=False)
            formulario.grupo = grupo
            formulario.user = request.user
            formulario.save()
            return redirect(f'/{grupo.slug}/')
        else:
            return render(request, self.template_name, {'form': form, 'slug_grupo': slug_grupo})

class VisualizarSubGrupo(GroupRequiredMixin, LoginRequiredMixin, ListView):
    group_required = (u"Auditores", u"SGCE", u"Inspetores Gerais", u"Supervisores")

    def get(self, request, slug_grupo, slug_subgrupo):
        busca = request.GET.get('search-area', '')
        subgrupo = get_object_or_404(SubGrupo, slug=slug_subgrupo, grupo__slug=slug_grupo)
        tarefas = subgrupo.tarefa_set.all()

        if busca:
            tarefas = tarefas.filter(nome___icontains=busca)

        context = {'tarefas': tarefas, 'subgrupo': subgrupo, 'search_input': busca}

        return render(request, "subgrupo/subgrupo.html", context)


class MostraSubGrupo(GroupRequiredMixin, LoginRequiredMixin, View):
    group_required = (u"Auditores", u"SGCE", u"Inspetores Gerais", u"Supervisores")

    def get(self, request, pk):
        subgrupo_especifico = SubGrupo.objects.get(id=pk)
        join_subgrupo = subgrupo_especifico.tarefa_subgrupos.all()
        id_grupo = subgrupo_especifico.grupo_sub_id

        busca = request.GET.get('search-area', '')

        if busca:
            join_subgrupo = join_subgrupo.filter(title__icontains=busca)

        context = {'join_subgrupo': join_subgrupo, 'pk': pk, 'search_input': busca, 'id_grupo': id_grupo}

        return render(request, "login/mostra_subgrupo.html", context)

class exclui_subgrupo(GroupRequiredMixin, LoginRequiredMixin, View):
    group_required = (u"SGCE", u"Inspetores Gerais")

    template_name = 'tarefa/excluir_subgrupo.html'
    model_form = SubGrupoForm

    def get(self, request, slug_grupo, pk):
        grupo = get_object_or_404(Grupo, slug=slug_grupo)
        subgrupo = get_object_or_404(SubGrupo, slug=slug_subgrupo)

        return render(request, self.template_name, {'subgrupo': subgrupo, 'grupo': slug_grupo})

    def post(self, request, slug_grupo, slug_subgrupo, pk):
        grupo = get_object_or_404(Grupo, slug=slug_grupo)
        subgrupo = get_object_or_404(SubGrupo, grupo=grupo, slug=slug_subgrupo)

        subgrupo.delete()

        return redirect('grupo:grupo', slug_grupo)

def edita_subgrupo(request, pk):
    item_id = SubGrupo.objects.get(id=pk)
    id_grupo = item_id.grupo_sub_id

    if request.method == 'POST':
        item = get_object_or_404(SubGrupo, id=pk)
        form = SubGrupoForm(request.POST, instance=item)

        if form.is_valid():
            form.save()
            return redirect(f'/subgrupos/{id_grupo}')
    else:
        item = SubGrupo.objects.filter(id=pk).values().last()
        form = SubGrupoForm(initial=item)

    return render(request, 'login/formulario_subgrupos.html', {'pk': pk, 'form': form, 'id_grupo': id_grupo})


def atualiza_subgrupo(request, pk):
    item = SubGrupo.objects.get(id=pk)
    id_grupo = item.grupo_sub_id

    if request.method == 'POST':
        item.delete()
        return redirect(f'/subgrupos/{id_grupo}')

    return render(request, 'login/apagar_subgrupo.html', {'pk': pk, 'id_grupo': id_grupo})


class AtualizarSubGrupo(LoginRequiredMixin, UpdateView):
    model = SubGrupo
    fields = '__all__'
    template_name = 'login/formulario_subgrupos.html'

templates/subgrupo/apagar_subgrupo.html
{% extends 'base.html' %}
{% block content %}

<a href="{% url 'subgrupos' id_grupo %} ">Retornar</a>

<form method='POST'>
  {% csrf_token %}
  <p>Tem certeza de que deseja apagar a questão {{ subgrupo }} ?</p>
  <input type="submit" value="ApagaSubGrupo">
</form>

{% endblock content %}

templates/subgrupo/formulario_subgrupo.html
{% extends 'base.html' %}
{% block content %}

<h3>Formulario</h3>

<a href="{% url 'grupo:grupo' slug_grupo %}">Retornar</a>

<form method="POST" action="">

  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="enviar">

</form>

{% endblock content %}

templates/subgrupo/subgrupo.html
{% extends 'base.html' %}
{% block content %}

  {% include "nav.html" %}

<div class='header-bar'>
    <div>
        <h1>Hello, {{ request.user.first_name }}</h1>
        <h3 style="margin:0">Você tem <i>{{ count }}</i> respostas revisadas.</h3>
        <h3 style="margin:0"> <a href="{% url 'home:index' %}">Assuntos</a></h3>
        <h3 style="margin:0"> <a href="{% url 'home:subgrupos' %}">Questionário</a></h3>
    </div>

{% if request.user.is_authenticated %}
       <a href="{% url 'logout' %}">Sair</a>
    {% else %}
        <a href="{% url 'login' %}">Entrar</a>
{% endif %}
</div>

<h1>Respostas
{% for author in author_list %}
    <li>{{ tarefas.name }}</li>
{% endfor %}
</h1>

<a id="add-link" href="{% url 'tarefa:criar' subgrupo.grupo.slug subgrupo.slug %}">&#x2b;</a>

<div id="tasklist" class="task-items-wrapper">
    {% for tarefa in tarefas %}
    <div class="task-wrapper" data-position="{{tarefa.pk}}">
        <div class="task-title">
            {% if tarefa.complete %}
                <div class="task-complete-icon"></div>
                <a href="{% url 'tarefa:atualizar' tarefa.grupo.slug tarefa.subgrupo.slug tarefa.id %}">{{tarefa}}</a>
            {% else %}
                <div class="task-incomplete-icon"></div>
                <a href="{% url 'tarefa:atualizar' tarefa.grupo.slug tarefa.subgrupo.slug tarefa.id %}">{{tarefa}}</a>
            {% endif %}
        </div>
        <div class="task-controls">
         <a class="delete-link" href="{% url 'tarefa:apagar' tarefa.grupo.slug tarefa.subgrupo.slug tarefa.id %}">&#215;</a>
            <span class="handle">&nbsp;&#10247;</span>
        </div>
    </div>

    {% empty %}
    <h3>No items in list</h3>
    {% endfor %}
</div>

<h1>Powered by CIEG</h1>

{% endblock content %}